class liga:
    def __init__(self, LEAGUE_NAME, COUNTRY_NAME, COUNTRY_ID, ACTUAL_TOURNAMENT_SEASON_ID, GROUP_ID, SEASON_ID, TEMPLATE_ID):
        self.LEAGUE_NAME = LEAGUE_NAME
        self.COUNTRY_NAME = COUNTRY_NAME
        self.COUNTRY_ID = COUNTRY_ID
        self.ACTUAL_TOURNAMENT_SEASON_ID = ACTUAL_TOURNAMENT_SEASON_ID
        self.SEASON_ID = SEASON_ID
        self.GROUP_ID = GROUP_ID
        self.SEASON_ID = SEASON_ID
        self.TEMPLATE_ID = TEMPLATE_ID


ligalocal = [
    liga(LEAGUE_NAME="Premier League", COUNTRY_NAME="England", COUNTRY_ID=198, ACTUAL_TOURNAMENT_SEASON_ID="nmP0jyrt",GROUP_ID="dYlOSQOD",SEASON_ID=176,TEMPLATE_ID="198_dYlOSQOD"),
    liga(LEAGUE_NAME="Bundes liga", COUNTRY_NAME="Germany", COUNTRY_ID=81, ACTUAL_TOURNAMENT_SEASON_ID="UHqzLeAl",GROUP_ID="W6BOzpK2",SEASON_ID=176,TEMPLATE_ID="81_W6BOzpK2"),
    liga(LEAGUE_NAME="Ligue 1", COUNTRY_NAME="France", COUNTRY_ID=77, ACTUAL_TOURNAMENT_SEASON_ID="hIyJ4mB7",GROUP_ID="KIShoMk3",SEASON_ID=176,TEMPLATE_ID="77_KIShoMk3"),
    liga(LEAGUE_NAME="Serie A", COUNTRY_NAME="Italy", COUNTRY_ID=98, ACTUAL_TOURNAMENT_SEASON_ID="hjqVKnQ0",GROUP_ID="COuk57Ci",SEASON_ID=176,TEMPLATE_ID="98_COuk57Ci"),
    liga(LEAGUE_NAME="La Liga", COUNTRY_NAME="Spain", COUNTRY_ID=176, ACTUAL_TOURNAMENT_SEASON_ID="lUpIrnCB",GROUP_ID="QVmLl54o",SEASON_ID=176,TEMPLATE_ID="176_QVmLl54o")
]
ligaeuropea=[
    liga(LEAGUE_NAME="Champions League", COUNTRY_NAME="Europe", COUNTRY_ID=6, ACTUAL_TOURNAMENT_SEASON_ID="46CxjEua",GROUP_ID="xGrwqq16",SEASON_ID=176,TEMPLATE_ID="6_xGrwqq16"),
    liga(LEAGUE_NAME="Europa League", COUNTRY_NAME="Europe", COUNTRY_ID=6, ACTUAL_TOURNAMENT_SEASON_ID="raK3iPRj",GROUP_ID="ClDjv3V5",SEASON_ID=176,TEMPLATE_ID="6_ClDjv3V5"),
    liga(LEAGUE_NAME="Europa Conference League", COUNTRY_NAME="Europe", COUNTRY_ID=6, ACTUAL_TOURNAMENT_SEASON_ID="nFZlkYf5",GROUP_ID="GfRbsVWM",SEASON_ID=176,TEMPLATE_ID="6_GfRbsVWM")
]
